# Generated by Django 5.0.1 on 2024-08-08 23:14

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('address', models.CharField(default=None, max_length=100)),
                ('state', models.CharField(default=None, max_length=100)),
                ('city', models.CharField(default=None, max_length=100)),
                ('description', models.TextField(default=None, null=True)),
                ('country', models.CharField(default=None, max_length=100)),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('beds', models.IntegerField()),
                ('sleeps', models.IntegerField(blank=True, null=True)),
                ('footage', models.IntegerField(blank=True, null=True)),
                ('bed_type', models.CharField(blank=True, max_length=100, null=True)),
                ('room_images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), size=None)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('check_in_date', models.DateField(default=None)),
                ('check_out_date', models.DateField(default=None)),
                ('reservation_price', models.FloatField(default=None)),
                ('num_of_rooms', models.IntegerField(default=None)),
                ('guest', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
        ),
    ]
