# Generated by Django 5.0.7 on 2024-07-31 22:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_room_reservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="image_url",
        ),
        migrations.AddField(
            model_name="hotel",
            name="amenities",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=100, null=True),
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="description",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="image_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="guest",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
